---
name: httpd
director_uuid: 365eb26d-146e-4d12-888f-d9249dbef375

release:
  name: static-syte
  version: latest

compilation:
  workers: 2
  network: default
  reuse_compilation_vms: true
  cloud_properties:
    instance_type: m1.small

update:
  canaries: 1
  canary_watch_time: 60000
  update_watch_time: 60000
  max_in_flight: 4
  max_errors: 1

networks:

- name: default
  subnets:
  - range: 10.244.1.0/24
    reserverd: 
      - 10.244.1.0
      - 10.244.1.255
      - 10.244.1.1
    static:
      - 10.244.1.2
    cloud_properties:
      name: random

resource_pools:
- name: common
  network: default
  size: 1
  stemcell:
    name: bosh-stemcell
    version: 993
  cloud_properties:
    instance_type: m1.small

jobs:
- name: httpd
  template: httpd
  instances: 1
  resource_pool: common
  networks:
  - name: default
    static_ips:
      - 10.244.1.2
    default:
    - dns
    - gateway

properties: {}